portal/src/App.tsx, portal/src/Home/Banner.tsx, portal/src/Home/static/home.css, portal/src/Model.ts, portal/src/RedashAPI.ts, portal/src/formatters.ts
=> feat: Show statistics in Welcome page

.github/workflows/portal.yml
=> fix: Worflows

.github/workflows/api.yml, README.md, api/Dockerfile, api/package.json, api/src/services/SearchPeople.ts, portal/src/pages/AboutPage.tsx
=> feat: Make the API more resilient

.github/workflows/airflow.yml, infra/airflow/docker-compose.yml, scripts/python/airflow/Dockerfile, scripts/python/airflow/dags/a_quien_elegimos.py, scripts/python/airflow/dags/batch_insert.py, scripts/python/airflow/dags/ds_table_operations.py, scripts/python/airflow/requirements.txt
=> feat: Add DAG for a_quien_elegimos

portal/src/pages/ActionResearchLanding.tsx
=> Change ActionResearch's title and description

.github/workflows/api.yml, .github/workflows/portal.yml, api/package.json, scripts/package.json
=> feat: Call hooks on successful job

portal/src/Model.ts, portal/src/components/person_cards/Charge.tsx, portal/src/components/person_cards/Hacienda.tsx, portal/src/components/person_cards/SFP.tsx, portal/src/pages/PersonDetailPage.tsx
=> portal improvements

migrations/R_Full_data_table.sql
=> feat: Add script that populates the main search table

portal/src/pages/OCDSSupplier.tsx
=> feat: Compare supplier with both sides of comparation

portal/src/components/person_cards/DDJJ.tsx
=> feat: Fix responsive on ddjj

portal/.gitignore, portal/src/pages/ElectedAuthoritiesPage.tsx
=> Añadir separador de miles en nro de documento en ElectedAuthoritiesPage

.github/workflows/airflow.yml, scripts/python/airflow/dags/a_quien_elegimos.py, scripts/python/airflow/dags/sfp_download_files.py
=> Fix dags start_date

portal/src/components/layout/Footer.css
=> fix: logo width for big screens

portal/src/pages/PersonSearchPage.css, portal/src/pages/PersonSearchPage.tsx, portal/yarn.lock
The filter for sources is now 'and', the current filters are now a list
of tags, and all the data is presented in cards.
=> feat: Improve Person search page

portal/src/pages/PersonSearchPage.tsx
=> Change color of 'source' in PersonSearchPage

scripts/python/airflow/dags/_muni_operators.py, scripts/python/airflow/dags/ds_table_operations.py, scripts/python/airflow/dags/muni_main_page_downloader.py, scripts/python/airflow/dags/network_operators.py, scripts/python/airflow/requirements.txt
=> feat: Add dag to download all files from asu-muni

scripts/python/airflow/dags/_csj_operators.py, scripts/python/airflow/dags/_mspbs_operators.py, scripts/python/airflow/dags/_policia_operators.py, scripts/python/airflow/dags/csj_downloader.py
=> DAG for csj

scripts/python/airflow/dags/_mspbs_operators.py, scripts/python/airflow/dags/mspbs_downloader.py
=> MSPB Downloader

scripts/python/airflow/dags/mspbs_downloader.py
=> fix: mspbs folder on ftp

.github/workflows/api.yml, .github/workflows/portal.yml, api/package.json, portal/package.json, portal/src/SimpleApi.ts, portal/src/components/layout/Footer.tsx
=> feat: Configure project to use semillas.controlciudadanopy.org

.github/workflows/api.yml, .github/workflows/portal.yml
=> feat: Allow github actions to publish semillas tag

migrations/V9__Authorities_with_ddjj.sql
=> Relation Authorities with declarations

api/src/services/Staging.ts, portal/src/Model.ts, portal/src/components/person_cards/TSJE.tsx, portal/src/pages/ElectedAuthoritiesPage.tsx, portal/src/pages/PersonDetailPage.tsx
=> fix: Columns of tsje_elected table

portal/package.json, portal/src/components/ddjj/HeatMap.tsx, portal/src/components/ddjj/ListChart.tsx, portal/yarn.lock
=> feat: Make map responsive

scripts/python/airflow/dags/contralory_declaration_link_fetcher.py
=> feat: Add new dag to download the full list of djbr

scripts/python/airflow/dags/contralory_declaration_download_pdfs.py, scripts/python/airflow/dags/file_system_helper.py, scripts/python/airflow/dags/network_operators.py
=> feat: Dag to download pdf form contralory new api

scripts/python/airflow/dags/contralory_declaration_download_pdfs.py
=> fix: Range of pdf djbr download

scripts/python/airflow/dags/contralory_declaration_download_pdfs.py, scripts/python/airflow/dags/network_operators.py
=> fix: Loop on contralory download pdfs dag

portal/src/pages/AffidavitList.tsx, portal/src/pages/PersonDetailPage.tsx
=> fix: Affidavit links

migrations/V10__View_djbr.sql, migrations/V9__Authorities_with_ddjj.sql, portal/src/Model.ts, portal/src/components/ddjj/CurrentFilters.tsx, portal/src/hooks/useStats.ts, portal/src/pages/DJBRDashboard.tsx
See https://github.com/InstIDEA/controlciudadano/issues/198 for more
details.
=> feat: Update texts in djbr dashboard

api/src/services/Staging.ts
=> fix: DJBR table on analysis query

api/package-lock.json, portal/src/Model.ts, portal/src/SimpleApi.ts, portal/src/pages/PersonDetailPage.tsx
=> feat: Update model to use new api schema

.github/workflows/api.yml, .github/workflows/portal.yml
=> feat: Config for develop.controlciudadanopy.org

portal/src/App.css, portal/src/analysis/AnalysisModel.ts, portal/src/analysis/components/net_worth/Calculations.tsx, portal/src/analysis/components/net_worth/Graphs.tsx, portal/src/analysis/components/net_worth/InputData.tsx, portal/src/analysis/pages/AnalysisNetWorthIncrement.tsx, portal/src/formatters.ts
=> feat: Add calculation in NetWorth analysis

.github/workflows/microservice_parser.yml, infra/services/docker-compose.yml
=> fix: Path of image on microservice compose

migrations/R_Full_data_table.sql, portal/src/pages/PersonSearchPage.tsx
=> feat: Ignore name of people with name 'VACANTE' of sfp

portal/src/components/ddjj/CurrentFilters.tsx, portal/src/components/person_cards/TSJE.tsx, portal/src/nameUtils.ts, portal/src/pages/PersonSearchPage.tsx
=> feat: Add charge filter to search person

portal/src/Model.ts, portal/src/hooks/useStats.ts, portal/src/pages/DJBRDashboard.tsx
=> feat: Update text on djbr dashboard

scripts/python/airflow/dags/contralory_declaration_extractor.py
=> feat: Add more data to DJBR dag parser

scripts/python/airflow/dags/contralory_declaration_extractor.py
=> feat: Handle cases when charge is None

scripts/python/airflow/dags/contralory_declaration_extractor.py
=> Improve djbr extractor error messages

scripts/python/airflow/dags/contralory_declaration_extractor.py
=> feat: Add info to psycopg2 exceptions

scripts/python/airflow/dags/contralory_declaration_extractor.py
=> feat: Add debugging info in extractor for removed rows

api/src/analysis/NetWorthAnalysis.ts, portal/src/analysis/NetWorthHook.ts, portal/src/analysis/components/net_worth/Graphs.tsx, portal/src/analysis/components/net_worth/InputData.tsx, portal/src/analysis/pages/AnalysisLanding.tsx, portal/src/analysis/pages/AnalysisNetWorthIncrement.tsx
=> Bug analysis net worth

portal/src/analysis/components/net_worth/Graphs.tsx
=> feat: Improve nw graphs tooltip

portal/src/Model.ts, portal/src/analysis/pages/AnalysisLanding.tsx, portal/src/hooks/useStats.ts
=> feat: Add one paragraph with stats in analysis landing

portal/src/analysis/pages/AnalysisLanding.tsx
=> fix: typo on analysis landing

scripts/python/airflow/dags/contralory_declaration_link_fetcher.py
- fix: Pagination of link fetcher
=> fix: Error on pagination of fetcher

scripts/python/airflow/dags/contralory_declaration_link_fetcher.py
=> fix: Upsert on link fetcher
